package presentacion.cuGenerarContrato;

import presentacion.*;
import control.ControlAltaResidente;
import javax.swing.JOptionPane;

/**
 * Ventana que confirma el alta exitosa de un residente en el sistema de residencias.
 * Muestra un mensaje de confirmacion y permite generar un contrato (no implementado) o regresar
 * al inicio. Extiende JFrameBase para heredar propiedades comunes de ventanas.
 */
public class FrmError extends JFrameBase {

    /**
     * Controlador para gestionar la logica de alta de residentes.
     */
    private ControlAltaResidente control;

    /**
     * Crea una nueva ventana FrmResidenteAltaExitosa.
     * Inicializa los componentes de la interfaz grafica.
     * @param control Controlador para la logica de alta de residentes
     */
    public FrmError(ControlAltaResidente control) {
        super();
        this.control = control;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresarInicio = new javax.swing.JButton();
        lblNombreResidente = new javax.swing.JLabel();
        lblLogoResi = new javax.swing.JLabel();
        lblPreview = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 44, 87));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        btnRegresarInicio.setBackground(new java.awt.Color(27, 44, 87));
        btnRegresarInicio.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        btnRegresarInicio.setForeground(new java.awt.Color(107, 225, 251));
        btnRegresarInicio.setText("Regresar a inicio");
        btnRegresarInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 225, 251), 2, true));
        btnRegresarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarInicioActionPerformed(evt);
            }
        });

        lblNombreResidente.setFont(new java.awt.Font("Apple LiGothic", 0, 100)); // NOI18N
        lblNombreResidente.setForeground(new java.awt.Color(107, 225, 251));
        lblNombreResidente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreResidente.setText("¡UPS!");
        lblNombreResidente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblLogoResi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logotipo Residencias Estudiantiles Horizontal.png"))); // NOI18N

        lblPreview.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblPreview.setForeground(new java.awt.Color(245, 253, 255));
        lblPreview.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPreview.setText("Ocurrió un error al procesar tu solicitud, vuelve a intentarlo");
        lblPreview.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(lblPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(btnRegresarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreResidente))))
                .addGap(174, 193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(lblLogoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombreResidente)
                .addGap(18, 18, 18)
                .addComponent(lblPreview)
                .addGap(58, 58, 58)
                .addComponent(btnRegresarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento del boton Regresar a Inicio.
     * Finaliza el caso de uso actual y regresa al menu principal.
     * @param evt Evento de accion del boton
     */
    private void btnRegresarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarInicioActionPerformed
       control.acabarCaso();
    }//GEN-LAST:event_btnRegresarInicioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogoResi;
    private javax.swing.JLabel lblNombreResidente;
    private javax.swing.JLabel lblPreview;
    // End of variables declaration//GEN-END:variables
}
