/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.cuGenerarContrato;

import control.ControlGenerarContrato;
import dto.FiadorDTO;
import dto.ResidenteDTO;
import implementaciones.FiadorDAO;
import javax.swing.JOptionPane;
import presentacion.JFrameBase;

/**
 *
 * @author abrilislas
 */
public class FrmRegistroFiador extends JFrameBase {
    
    ControlGenerarContrato control;
    ResidenteDTO residenteDTO;
    FiadorDTO nuevoFiadorDTO;
    
    /**
     * 
     * @param control 
     */
    public FrmRegistroFiador(ControlGenerarContrato control) {
        super();
        initComponents();
        this.control = control;
        grupoBtnPlanPago.add(radioBtnContado);
        grupoBtnPlanPago.add(radioBtnMitadTres);
        grupoBtnPlanPago.add(radioBtnMensual);
    }
    
    /**
     * Se obtiene el residente correspondiente al fiador y se muestra en pantalla
     * @param residenteDTO 
     */
    public void obtenerResidente(ResidenteDTO residenteDTO){
        this.residenteDTO=residenteDTO;
        lblResidenteAsignado.setText(residenteDTO.getNombreCompleto());
    }
    public ResidenteDTO devolverResidenteActualizado(){
        return residenteDTO;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBtnPlanPago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        pnlLinea = new javax.swing.JPanel();
        labelID1 = new javax.swing.JLabel();
        nombreCompletoFiadorTXT = new javax.swing.JTextField();
        labelID = new javax.swing.JLabel();
        ocupacionFiadorTXT = new javax.swing.JTextField();
        labelID3 = new javax.swing.JLabel();
        direccionFiadorTXT = new javax.swing.JTextField();
        labelID2 = new javax.swing.JLabel();
        telefonoFiadorTXT = new javax.swing.JTextField();
        labelID4 = new javax.swing.JLabel();
        relacionResidenteTXT = new javax.swing.JTextField();
        lblLogoResi = new javax.swing.JLabel();
        lblResponsable = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nombreResidenteTXT = new javax.swing.JLabel();
        radioBtnContado = new javax.swing.JRadioButton();
        radioBtnMitadTres = new javax.swing.JRadioButton();
        radioBtnMensual = new javax.swing.JRadioButton();
        lblResidenteAsignado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 44, 87));

        lblTitulo.setFont(new java.awt.Font("Apple LiGothic", 0, 70)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(245, 253, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("Registro de Fiador");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        panelInfo.setBackground(new java.awt.Color(37, 55, 95));

        pnlLinea.setBackground(new java.awt.Color(107, 225, 251));

        javax.swing.GroupLayout pnlLineaLayout = new javax.swing.GroupLayout(pnlLinea);
        pnlLinea.setLayout(pnlLineaLayout);
        pnlLineaLayout.setHorizontalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        pnlLineaLayout.setVerticalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        labelID1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelID1.setForeground(new java.awt.Color(204, 204, 204));
        labelID1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID1.setText("Nombre completo");
        labelID1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        nombreCompletoFiadorTXT.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
        nombreCompletoFiadorTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCompletoFiadorTXTActionPerformed(evt);
            }
        });

        labelID.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelID.setForeground(new java.awt.Color(204, 204, 204));
        labelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID.setText("Ocupación");
        labelID.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        ocupacionFiadorTXT.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
        ocupacionFiadorTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocupacionFiadorTXTActionPerformed(evt);
            }
        });

        labelID3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelID3.setForeground(new java.awt.Color(204, 204, 204));
        labelID3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID3.setText("Dirección");
        labelID3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        direccionFiadorTXT.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
        direccionFiadorTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionFiadorTXTActionPerformed(evt);
            }
        });

        labelID2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelID2.setForeground(new java.awt.Color(204, 204, 204));
        labelID2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID2.setText("Teléfono");
        labelID2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        telefonoFiadorTXT.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
        telefonoFiadorTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoFiadorTXTActionPerformed(evt);
            }
        });

        labelID4.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelID4.setForeground(new java.awt.Color(204, 204, 204));
        labelID4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID4.setText("Relación con el residente");
        labelID4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        relacionResidenteTXT.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
        relacionResidenteTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacionResidenteTXTActionPerformed(evt);
            }
        });

        lblLogoResi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logotipo Residencias Estudiantiles Horizontal.png"))); // NOI18N

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelID1)
                            .addComponent(nombreCompletoFiadorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ocupacionFiadorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelID)
                            .addComponent(labelID3)
                            .addComponent(direccionFiadorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoFiadorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelID2)
                            .addComponent(labelID4)
                            .addComponent(relacionResidenteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblLogoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblLogoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(labelID1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreCompletoFiadorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocupacionFiadorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelID3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionFiadorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelID2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoFiadorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelID4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relacionResidenteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblResponsable.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblResponsable.setForeground(new java.awt.Color(0, 153, 255));
        lblResponsable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResponsable.setText("Responsable del pago de la renta");
        lblResponsable.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnRegresar.setBackground(new java.awt.Color(37, 55, 95));
        btnRegresar.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(107, 225, 251));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 225, 251), 1, true));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(107, 225, 251));
        btnRegistrar.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(27, 44, 87));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        nombreResidenteTXT.setBackground(new java.awt.Color(255, 255, 255));
        nombreResidenteTXT.setFont(new java.awt.Font("Cambay Devanagari", 0, 30)); // NOI18N
        nombreResidenteTXT.setForeground(new java.awt.Color(51, 51, 51));
        nombreResidenteTXT.setText("Selección de plan");

        radioBtnContado.setText("Pago de contado de 18,732.00 MX");
        radioBtnContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnContadoActionPerformed(evt);
            }
        });

        radioBtnMitadTres.setText("Mitad y tres pagos 9,958.00 y 3286.00 MX");

        radioBtnMensual.setText("4 pagos de 5,127.00 MX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnMensual)
                    .addComponent(radioBtnMitadTres)
                    .addComponent(radioBtnContado)
                    .addComponent(nombreResidenteTXT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(nombreResidenteTXT)
                .addGap(18, 18, 18)
                .addComponent(radioBtnContado)
                .addGap(18, 18, 18)
                .addComponent(radioBtnMitadTres)
                .addGap(18, 18, 18)
                .addComponent(radioBtnMensual)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        lblResidenteAsignado.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblResidenteAsignado.setForeground(new java.awt.Color(255, 255, 255));
        lblResidenteAsignado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResidenteAsignado.setText("Responsable del pago de la renta");
        lblResidenteAsignado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitulo)
                    .addComponent(lblResponsable)
                    .addComponent(lblResidenteAsignado))
                .addGap(18, 18, 18)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblResponsable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResidenteAsignado)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Se crea un fiadorDTO con los datos ingresados en el formulario y se envia a control
     * @param evt 
     */
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       String nombreCompleto = nombreCompletoFiadorTXT.getText();
       String ocupacion = ocupacionFiadorTXT.getText();
       String relacionResidente = relacionResidenteTXT.getText();
       String direccion= direccionFiadorTXT.getText();
       String numeroTelefono = telefonoFiadorTXT.getText();
       
        nuevoFiadorDTO = new FiadorDTO( nombreCompleto,ocupacion, direccion,numeroTelefono,relacionResidente);
        try{
            control.registrarFiador(nuevoFiadorDTO,residenteDTO);
            this.residenteDTO.setAdeudo(grupoBtnPlanPago.getSelection().toString());
            control.abrirPantallaDescarga(residenteDTO);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        //control.previewResidente(residenteDTO);
        control.registrarFiador(nuevoFiadorDTO, residenteDTO);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void telefonoFiadorTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoFiadorTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoFiadorTXTActionPerformed

    private void nombreCompletoFiadorTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCompletoFiadorTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCompletoFiadorTXTActionPerformed

    private void ocupacionFiadorTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocupacionFiadorTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocupacionFiadorTXTActionPerformed

    private void direccionFiadorTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionFiadorTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionFiadorTXTActionPerformed

    private void relacionResidenteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacionResidenteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relacionResidenteTXTActionPerformed

    private void radioBtnContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnContadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnContadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField direccionFiadorTXT;
    private javax.swing.ButtonGroup grupoBtnPlanPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelID1;
    private javax.swing.JLabel labelID2;
    private javax.swing.JLabel labelID3;
    private javax.swing.JLabel labelID4;
    private javax.swing.JLabel lblLogoResi;
    private javax.swing.JLabel lblResidenteAsignado;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField nombreCompletoFiadorTXT;
    private javax.swing.JLabel nombreResidenteTXT;
    private javax.swing.JTextField ocupacionFiadorTXT;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel pnlLinea;
    private javax.swing.JRadioButton radioBtnContado;
    private javax.swing.JRadioButton radioBtnMensual;
    private javax.swing.JRadioButton radioBtnMitadTres;
    private javax.swing.JTextField relacionResidenteTXT;
    private javax.swing.JTextField telefonoFiadorTXT;
    // End of variables declaration//GEN-END:variables
}
