/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.cuGenerarContrato;

import presentacion.JFrameBase;

/**
 *
 * @author abrilislas
 */
public class JFrameRegistroFiador extends JFrameBase {

    /**
     * Creates new form JFrameRegistroFiador
     */
    public JFrameRegistroFiador() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        pnlLinea = new javax.swing.JPanel();
        labelID1 = new javax.swing.JLabel();
        campoTextoID2 = new javax.swing.JTextField();
        labelID = new javax.swing.JLabel();
        campoTextoID3 = new javax.swing.JTextField();
        labelID3 = new javax.swing.JLabel();
        campoTextoID4 = new javax.swing.JTextField();
        labelID2 = new javax.swing.JLabel();
        campoTextoID1 = new javax.swing.JTextField();
        labelID4 = new javax.swing.JLabel();
        campoTextoID5 = new javax.swing.JTextField();
        lblLogoResi = new javax.swing.JLabel();
        labelHabitacionSeleccionada = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nombreResidenteTXT = new javax.swing.JLabel();
        radioBtnContado = new javax.swing.JRadioButton();
        radioBtnMitadTres = new javax.swing.JRadioButton();
        radioBtnMensual = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 44, 87));

        lblTitulo.setFont(new java.awt.Font("Apple LiGothic", 0, 70)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(245, 253, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("Registro de Fiador");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        panelInfo.setBackground(new java.awt.Color(37, 55, 95));

        pnlLinea.setBackground(new java.awt.Color(107, 225, 251));

        javax.swing.GroupLayout pnlLineaLayout = new javax.swing.GroupLayout(pnlLinea);
        pnlLinea.setLayout(pnlLineaLayout);
        pnlLineaLayout.setHorizontalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        pnlLineaLayout.setVerticalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        labelID1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelID1.setForeground(new java.awt.Color(204, 204, 204));
        labelID1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID1.setText("Nombre completo");
        labelID1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        campoTextoID2.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
        campoTextoID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoID2ActionPerformed(evt);
            }
        });

        labelID.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelID.setForeground(new java.awt.Color(204, 204, 204));
        labelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID.setText("Ocupación");
        labelID.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        campoTextoID3.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
        campoTextoID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoID3ActionPerformed(evt);
            }
        });

        labelID3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelID3.setForeground(new java.awt.Color(204, 204, 204));
        labelID3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID3.setText("Dirección");
        labelID3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        campoTextoID4.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
        campoTextoID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoID4ActionPerformed(evt);
            }
        });

        labelID2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelID2.setForeground(new java.awt.Color(204, 204, 204));
        labelID2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID2.setText("Teléfono");
        labelID2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        campoTextoID1.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
        campoTextoID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoID1ActionPerformed(evt);
            }
        });

        labelID4.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelID4.setForeground(new java.awt.Color(204, 204, 204));
        labelID4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID4.setText("Relación con el residente");
        labelID4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        campoTextoID5.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
        campoTextoID5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoID5ActionPerformed(evt);
            }
        });

        lblLogoResi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logotipo Residencias Estudiantiles Horizontal.png"))); // NOI18N

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelID1)
                            .addComponent(campoTextoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelID)
                            .addComponent(labelID3)
                            .addComponent(campoTextoID4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoID1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelID2)
                            .addComponent(labelID4)
                            .addComponent(campoTextoID5, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblLogoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblLogoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(labelID1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelID3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoID4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelID2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoID1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelID4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoID5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelHabitacionSeleccionada.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        labelHabitacionSeleccionada.setForeground(new java.awt.Color(0, 153, 255));
        labelHabitacionSeleccionada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHabitacionSeleccionada.setText("Responsable del pago de la renta");
        labelHabitacionSeleccionada.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnRegresar.setBackground(new java.awt.Color(37, 55, 95));
        btnRegresar.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(107, 225, 251));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 225, 251), 1, true));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(107, 225, 251));
        btnRegistrar.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(27, 44, 87));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        nombreResidenteTXT.setBackground(new java.awt.Color(255, 255, 255));
        nombreResidenteTXT.setFont(new java.awt.Font("Cambay Devanagari", 0, 30)); // NOI18N
        nombreResidenteTXT.setForeground(new java.awt.Color(51, 51, 51));
        nombreResidenteTXT.setText("Selección de plan");

        radioBtnContado.setText("Pago de contado de 18,732.00 MX");
        radioBtnContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnContadoActionPerformed(evt);
            }
        });

        radioBtnMitadTres.setText("Mitad y tres pagos 9,958.00 y 3286.00 MX");

        radioBtnMensual.setText("4 pagos de 5,127.00 MX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnMensual)
                    .addComponent(radioBtnMitadTres)
                    .addComponent(radioBtnContado)
                    .addComponent(nombreResidenteTXT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(nombreResidenteTXT)
                .addGap(18, 18, 18)
                .addComponent(radioBtnContado)
                .addGap(18, 18, 18)
                .addComponent(radioBtnMitadTres)
                .addGap(18, 18, 18)
                .addComponent(radioBtnMensual)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitulo)
                    .addComponent(labelHabitacionSeleccionada))
                .addGap(18, 18, 18)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(labelHabitacionSeleccionada)
                .addGap(52, 52, 52)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void campoTextoID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoID1ActionPerformed

    private void campoTextoID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoID2ActionPerformed

    private void campoTextoID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoID3ActionPerformed

    private void campoTextoID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoID4ActionPerformed

    private void campoTextoID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoID5ActionPerformed

    private void radioBtnContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnContadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnContadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistroFiador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistroFiador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistroFiador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistroFiador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRegistroFiador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField campoTextoID1;
    private javax.swing.JTextField campoTextoID2;
    private javax.swing.JTextField campoTextoID3;
    private javax.swing.JTextField campoTextoID4;
    private javax.swing.JTextField campoTextoID5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelHabitacionSeleccionada;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelID1;
    private javax.swing.JLabel labelID2;
    private javax.swing.JLabel labelID3;
    private javax.swing.JLabel labelID4;
    private javax.swing.JLabel lblLogoResi;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel nombreResidenteTXT;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel pnlLinea;
    private javax.swing.JRadioButton radioBtnContado;
    private javax.swing.JRadioButton radioBtnMensual;
    private javax.swing.JRadioButton radioBtnMitadTres;
    // End of variables declaration//GEN-END:variables
}
