package presentacion;

<<<<<<< HEAD
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JLabel;
=======
import control.ControlAltaResidente;
import dto.ResidenteDTO;
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452

public class FrmInfoEstudiante1 extends javax.swing.JFrame {

    private ControlAltaResidente control;
    /**
     * Creates new form FrmInfoEstudiante
     */
    public FrmInfoEstudiante1(ControlAltaResidente control) {
        this.control = control;
        initComponents();
    }

    /**
     * Carga la información del estudiante en los inputs para mostrarla
     * @param estudiante DTO con la información del estudiante
     */
    public void cargarEstudiante(ResidenteDTO estudiante){
        String matricula = estudiante.getMatricula();
        String nombreCompleto = estudiante.getNombreCompleto();
        int semestre = estudiante.getSemestre();
        String carrera = estudiante.getCarrera();
        String telefono = estudiante.getTelefono();
        String direccion = estudiante.getDireccion();
        
        this.campoTextoID1.setText(matricula);
        this.campoTextoNombre.setText(nombreCompleto);
        this.campoTextoSemestre.setText(Integer.toString(semestre));
        this.campoTextoCarrera.setText(carrera);
        this.campoTextoNum.setText(telefono);
        this.campoTextoDireccion.setText(direccion);
        
        this.campoTextoID1.setEnabled(false);
        this.campoTextoNombre.setEnabled(false);
        this.campoTextoSemestre.setEnabled(false);
        this.campoTextoCarrera.setEnabled(false);
        this.campoTextoNum.setEnabled(false);
        this.campoTextoDireccion.setEnabled(false);
    }
    
    private void limpiarCampos(){
        this.campoTextoID1.setText("");
        this.campoTextoNombre.setText("");
        this.campoTextoSemestre.setText("");
        this.campoTextoCarrera.setText("");
        this.campoTextoNum.setText("");
        this.campoTextoDireccion.setText("");
        this.campoTextoNombreContactoEmergencia.setText("");
        this.campoTextoNumContactoEmergencia.setText("");
        
        this.campoTextoID1.setEnabled(true);
        this.campoTextoNombre.setEnabled(true);
        this.campoTextoSemestre.setEnabled(true);
        this.campoTextoCarrera.setEnabled(true);
        this.campoTextoNum.setEnabled(true);
        this.campoTextoDireccion.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
<<<<<<< HEAD
        carreraTXT = new javax.swing.JLabel();
        TxtField_Carrera = new javax.swing.JTextField();
        idEstudianteTXT1 = new javax.swing.JLabel();
        TxtField_ID = new javax.swing.JTextField();
        nombreTXT = new javax.swing.JLabel();
        TxtField_Nombre = new javax.swing.JTextField();
        TxtField_Semestre = new javax.swing.JTextField();
        semestreTXT = new javax.swing.JLabel();
        telefonoTXT = new javax.swing.JLabel();
        TxtField_TelefonoContacto = new javax.swing.JTextField();
        telefonoContactoTXT = new javax.swing.JLabel();
        direccionTXT = new javax.swing.JLabel();
        TxtField_Contacto = new javax.swing.JTextField();
        contactoTXT = new javax.swing.JLabel();
        TxtField_Direccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LabelActualizarInformacion = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        TxtField_Telefono = new javax.swing.JTextField();
=======
        idEstudianteTXT = new javax.swing.JLabel();
        campoTextoCarrera = new javax.swing.JTextField();
        idEstudianteTXT1 = new javax.swing.JLabel();
        campoTextoID1 = new javax.swing.JTextField();
        idEstudianteTXT2 = new javax.swing.JLabel();
        campoTextoNombre = new javax.swing.JTextField();
        campoTextoSemestre = new javax.swing.JTextField();
        idEstudianteTXT3 = new javax.swing.JLabel();
        idEstudianteTXT4 = new javax.swing.JLabel();
        campoTextoNumContactoEmergencia = new javax.swing.JTextField();
        idEstudianteTXT5 = new javax.swing.JLabel();
        idEstudianteTXT6 = new javax.swing.JLabel();
        campoTextoNombreContactoEmergencia = new javax.swing.JTextField();
        idEstudianteTXT7 = new javax.swing.JLabel();
        campoTextoDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnObtenerInformacion = new javax.swing.JButton();
        btnObtenerInformacion1 = new javax.swing.JButton();
        campoTextoNum = new javax.swing.JTextField();
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452
        altaResidentesTXT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 233, 236));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_ITSON.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        carreraTXT.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        carreraTXT.setText("CARRERA");

<<<<<<< HEAD
        TxtField_Carrera.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
=======
        campoTextoCarrera.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452

        idEstudianteTXT1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        idEstudianteTXT1.setText("ID ESTUDIANTE");

        TxtField_ID.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N

        nombreTXT.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nombreTXT.setText("NOMBRE");

<<<<<<< HEAD
        TxtField_Nombre.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N

        TxtField_Semestre.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
=======
        campoTextoNombre.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N

        campoTextoSemestre.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452

        semestreTXT.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        semestreTXT.setText("SEMESTRE");

        telefonoTXT.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        telefonoTXT.setText("NÚMERO DE TELÉFONO");

<<<<<<< HEAD
        TxtField_TelefonoContacto.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
=======
        campoTextoNumContactoEmergencia.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452

        telefonoContactoTXT.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        telefonoContactoTXT.setText("NÚMERO DE TELÉFONO DEL CONTACTO");

        direccionTXT.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        direccionTXT.setText("DIRECCIÓN");

<<<<<<< HEAD
        TxtField_Contacto.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
=======
        campoTextoNombreContactoEmergencia.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452

        contactoTXT.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        contactoTXT.setText("CONTACTO DE EMERGENCIA");

<<<<<<< HEAD
        TxtField_Direccion.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
=======
        campoTextoDireccion.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452

        LabelActualizarInformacion.setFont(new java.awt.Font("Al Bayan", 0, 12)); // NOI18N
        LabelActualizarInformacion.setForeground(new java.awt.Color(0, 153, 255));
        LabelActualizarInformacion.setText("La información fue actualizada por última vez: ");

        btnAlta.setBackground(new java.awt.Color(52, 47, 51));
        btnAlta.setForeground(new java.awt.Color(250, 250, 250));
        btnAlta.setText("DAR DE ALTA");
        btnAlta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(228, 233, 236));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        TxtField_Telefono.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
=======
        campoTextoNum.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 18)); // NOI18N
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452

        altaResidentesTXT.setFont(new java.awt.Font("Kohinoor Gujarati", 1, 50)); // NOI18N
        altaResidentesTXT.setText("ALTA DE RESIDENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carreraTXT)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idEstudianteTXT1)
<<<<<<< HEAD
                                .addComponent(nombreTXT)
                                .addComponent(semestreTXT)
                                .addComponent(TxtField_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                .addComponent(TxtField_Carrera)
                                .addComponent(TxtField_Semestre)
                                .addComponent(TxtField_ID))
=======
                                .addComponent(idEstudianteTXT2)
                                .addComponent(idEstudianteTXT3)
                                .addComponent(campoTextoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                .addComponent(campoTextoCarrera)
                                .addComponent(campoTextoSemestre)
                                .addComponent(campoTextoID1))
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(jLabel2))
                            .addComponent(LabelActualizarInformacion))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
<<<<<<< HEAD
                            .addComponent(telefonoTXT)
                            .addComponent(direccionTXT)
                            .addComponent(contactoTXT)
                            .addComponent(telefonoContactoTXT)
                            .addComponent(TxtField_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                            .addComponent(TxtField_Direccion)
                            .addComponent(TxtField_Contacto)
                            .addComponent(TxtField_TelefonoContacto)))
=======
                            .addComponent(idEstudianteTXT4)
                            .addComponent(idEstudianteTXT6)
                            .addComponent(idEstudianteTXT7)
                            .addComponent(idEstudianteTXT5)
                            .addComponent(campoTextoNum, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                            .addComponent(campoTextoDireccion)
                            .addComponent(campoTextoNombreContactoEmergencia)
                            .addComponent(campoTextoNumContactoEmergencia)))
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(altaResidentesTXT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(592, 592, 592)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(altaResidentesTXT)
                                .addGap(31, 31, 31)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonoTXT)
                            .addComponent(idEstudianteTXT1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtField_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(direccionTXT)
                            .addComponent(nombreTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtField_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(semestreTXT)
                            .addComponent(contactoTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtField_Semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtField_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carreraTXT)
                            .addComponent(telefonoContactoTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtField_Carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtField_TelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelActualizarInformacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
<<<<<<< HEAD
=======
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoID1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEstudianteTXT6)
                    .addComponent(idEstudianteTXT2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEstudianteTXT3)
                    .addComponent(idEstudianteTXT7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoNombreContactoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEstudianteTXT)
                    .addComponent(idEstudianteTXT5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoNumContactoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        FrmTipoResidente frmTipoResidente = new FrmTipoResidente();
        frmTipoResidente.setVisible(true);
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

<<<<<<< HEAD
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInfoEstudiante1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInfoEstudiante1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInfoEstudiante1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInfoEstudiante1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInfoEstudiante1().setVisible(true);
                
                // JLabel ActualizarInformacion2;
                //GregorianCalendar gcalendario = new GregorianCalendar();
                //LabelActualizarInformacion.setText(gcalendario.get(Calendar.DATE) + LabelActualizarInformacion.getText());
                }
        });
    }

=======
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelActualizarInformacion;
    private javax.swing.JTextField TxtField_Carrera;
    private javax.swing.JTextField TxtField_Contacto;
    private javax.swing.JTextField TxtField_Direccion;
    private javax.swing.JTextField TxtField_ID;
    private javax.swing.JTextField TxtField_Nombre;
    private javax.swing.JTextField TxtField_Semestre;
    private javax.swing.JTextField TxtField_Telefono;
    private javax.swing.JTextField TxtField_TelefonoContacto;
    private javax.swing.JLabel altaResidentesTXT;
<<<<<<< HEAD
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel carreraTXT;
    private javax.swing.JLabel contactoTXT;
    private javax.swing.JLabel direccionTXT;
=======
    private javax.swing.JButton btnObtenerInformacion;
    private javax.swing.JButton btnObtenerInformacion1;
    private javax.swing.JTextField campoTextoCarrera;
    private javax.swing.JTextField campoTextoDireccion;
    private javax.swing.JTextField campoTextoID1;
    private javax.swing.JTextField campoTextoNombre;
    private javax.swing.JTextField campoTextoNombreContactoEmergencia;
    private javax.swing.JTextField campoTextoNum;
    private javax.swing.JTextField campoTextoNumContactoEmergencia;
    private javax.swing.JTextField campoTextoSemestre;
    private javax.swing.JLabel idEstudianteTXT;
>>>>>>> a31ccb5680d3d5417b244e17a4fe2b1fed332452
    private javax.swing.JLabel idEstudianteTXT1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreTXT;
    private javax.swing.JLabel semestreTXT;
    private javax.swing.JLabel telefonoContactoTXT;
    private javax.swing.JLabel telefonoTXT;
    // End of variables declaration//GEN-END:variables
}
