package presentacion;

import java.util.List;

import control.ControlAltaResidente;
import dto.HabitacionDTO;
import dto.ResidenteDTO;

public class FrmAsignarHabitacionPrueba extends JFrameBase{

    private ControlAltaResidente control;
    private ResidenteDTO residente;

    /**
     * Creates new form FrmAsignarHabitacion
     */
    public FrmAsignarHabitacionPrueba(ControlAltaResidente control) {
        super();
        this.control = control;
        initComponents();
    }
   
        public void cargarInfo(ResidenteDTO residente){
        this.idResidenteTXT.setText("ID: "+residente.getMatricula());
        this.nombreResidenteTXT.setText(residente.getNombreCompleto());
        this.programaEducativoTXT.setText("Programa Educativo: "+residente.getCarrera());
        this.tipoResidenteTXT.setText("Tipo de residente: "+residente.getTipoResidente());
    }
        
        public void habitacionesDisponibles(List<HabitacionDTO> habitaciones) {
            String piso = comboBoxPiso.getSelectedItem().toString();

            List<HabitacionDTO> numeros = control.getHabitacionesDisponibles();
                for (HabitacionDTO numero : numeros) {
                    if (numero.isOcupada()){
                        break;
                    }else{
                       List<ResidenteDTO> residenteActual = numero.getResidentesActuales();
                        for (ResidenteDTO residenteDTO : residenteActual) {
                            if(this.residente.getTipoResidente().equals(residenteDTO.getTipoResidente())){
                                comboBoxHabitacionesRecomendadas.addItem(String.valueOf(numero.getNumeroHabitacion()));
                            
                            };
                        }
                    }
                }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        nombreResidenteTXT = new javax.swing.JLabel();
        idResidenteTXT = new javax.swing.JLabel();
        programaEducativoTXT = new javax.swing.JLabel();
        tipoResidenteTXT = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelNumHabitacion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        comboBoxHabitacionesRecomendadas = new javax.swing.JComboBox<>();
        labelNumHabitacion1 = new javax.swing.JLabel();
        labelNumHabitacion3 = new javax.swing.JLabel();
        comboBoxPiso = new javax.swing.JComboBox<>();
        labelNumHabitacion4 = new javax.swing.JLabel();
        labelHabitacionSeleccionada = new javax.swing.JLabel();
        btnAsignar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAsignar1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnAsignar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 233, 236));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_ITSON.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        panelInfo.setBackground(new java.awt.Color(255, 255, 255));

        nombreResidenteTXT.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 24)); // NOI18N
        nombreResidenteTXT.setText("Nombre del Residente");

        idResidenteTXT.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 11)); // NOI18N
        idResidenteTXT.setForeground(new java.awt.Color(51, 51, 51));
        idResidenteTXT.setText("ID: 0000000000");

        programaEducativoTXT.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 11)); // NOI18N
        programaEducativoTXT.setForeground(new java.awt.Color(51, 51, 51));
        programaEducativoTXT.setText("Programa educativo: Placeholder");

        tipoResidenteTXT.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 11)); // NOI18N
        tipoResidenteTXT.setForeground(new java.awt.Color(51, 51, 51));
        tipoResidenteTXT.setText("Tipo de residente placholder");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoResidenteTXT)
                    .addComponent(idResidenteTXT)
                    .addComponent(nombreResidenteTXT)
                    .addComponent(programaEducativoTXT))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(nombreResidenteTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idResidenteTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(programaEducativoTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoResidenteTXT)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        labelNumHabitacion.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 10)); // NOI18N
        labelNumHabitacion.setForeground(new java.awt.Color(101, 182, 121));
        labelNumHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNumHabitacion.setText("Habitaciones recomendadas:");
        labelNumHabitacion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPanel3.setBackground(new java.awt.Color(227, 227, 227));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        comboBoxHabitacionesRecomendadas.setBackground(new java.awt.Color(204, 255, 204));
        comboBoxHabitacionesRecomendadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxHabitacionesRecomendadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxHabitacionesRecomendadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxHabitacionesRecomendadas, 0, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(comboBoxHabitacionesRecomendadas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        labelNumHabitacion1.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 14)); // NOI18N
        labelNumHabitacion1.setForeground(new java.awt.Color(102, 102, 102));
        labelNumHabitacion1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNumHabitacion1.setText("Número de habitación");
        labelNumHabitacion1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        labelNumHabitacion3.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 14)); // NOI18N
        labelNumHabitacion3.setForeground(new java.awt.Color(102, 102, 102));
        labelNumHabitacion3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNumHabitacion3.setText("Piso:");
        labelNumHabitacion3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboBoxPiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        comboBoxPiso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxPisoItemStateChanged(evt);
            }
        });
        comboBoxPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPisoActionPerformed(evt);
            }
        });

        labelNumHabitacion4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        labelNumHabitacion4.setForeground(new java.awt.Color(102, 102, 102));
        labelNumHabitacion4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNumHabitacion4.setText("Habitación seleccionada:");
        labelNumHabitacion4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        labelHabitacionSeleccionada.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 14)); // NOI18N
        labelHabitacionSeleccionada.setForeground(new java.awt.Color(0, 102, 204));
        labelHabitacionSeleccionada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHabitacionSeleccionada.setText("0000");
        labelHabitacionSeleccionada.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnAsignar.setBackground(new java.awt.Color(153, 153, 153));
        btnAsignar.setFont(new java.awt.Font("InaiMathi", 1, 14)); // NOI18N
        btnAsignar.setForeground(new java.awt.Color(238, 238, 238));
        btnAsignar.setText("Selección manual");
        btnAsignar.setBorderPainted(false);
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(labelNumHabitacion1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelNumHabitacion3))
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelNumHabitacion)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelNumHabitacion4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelHabitacionSeleccionada))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumHabitacion3)
                            .addComponent(comboBoxPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNumHabitacion1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(labelNumHabitacion)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumHabitacion4)
                    .addComponent(labelHabitacionSeleccionada))
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Habitaciones disponibles.");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnAsignar1.setBackground(new java.awt.Color(51, 51, 51));
        btnAsignar1.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnAsignar1.setForeground(new java.awt.Color(204, 204, 204));
        btnAsignar1.setText("Regresar");
        btnAsignar1.setBorderPainted(false);
        btnAsignar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignar1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        btnAsignar2.setBackground(new java.awt.Color(102, 153, 255));
        btnAsignar2.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        btnAsignar2.setForeground(new java.awt.Color(227, 238, 247));
        btnAsignar2.setText("Asignar habitación");
        btnAsignar2.setBorderPainted(false);
        btnAsignar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAsignar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAsignar2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAsignar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxPisoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxPisoItemStateChanged

    }//GEN-LAST:event_comboBoxPisoItemStateChanged

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
       try{ 
           control.mostrarAsignarHabitacion();
           
       }catch(Exception e){
           e.getMessage();
       }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnAsignar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignar1ActionPerformed

    private void comboBoxHabitacionesRecomendadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxHabitacionesRecomendadasActionPerformed
    }//GEN-LAST:event_comboBoxHabitacionesRecomendadasActionPerformed

    private void btnAsignar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignar2ActionPerformed

    private void comboBoxPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPisoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnAsignar1;
    private javax.swing.JButton btnAsignar2;
    private javax.swing.JComboBox<String> comboBoxHabitacionesRecomendadas;
    private javax.swing.JComboBox<String> comboBoxPiso;
    private javax.swing.JLabel idResidenteTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelHabitacionSeleccionada;
    private javax.swing.JLabel labelNumHabitacion;
    private javax.swing.JLabel labelNumHabitacion1;
    private javax.swing.JLabel labelNumHabitacion3;
    private javax.swing.JLabel labelNumHabitacion4;
    private javax.swing.JLabel nombreResidenteTXT;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JLabel programaEducativoTXT;
    private javax.swing.JLabel tipoResidenteTXT;
    // End of variables declaration//GEN-END:variables
}
