package presentacion;

import java.util.List;

import excepciones.NegocioException;
import control.ControlActualizarResidente;
import control.ControlAltaResidente;
import dto.HabitacionDTO;
import dto.ResidenteDTO;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import administradorHabitaciones.AdministradorHabitacionesFachada;
import administradorHabitaciones.IAdministradorHabitaciones;

/**
 * Ventana para asignar manualmente una habitacion a un residente.
 * Permite seleccionar un piso y un numero de habitacion disponible, confirmando
 * la asignacion tras validar la seleccion. Cierra la ventana al completar la
 * asignacion.
 */
public class FrmAsignarHabitacionManual extends JFrame {

        /**
         * Controlador para gestionar la logica de alta de residentes y asignacion de
         * habitaciones.
         */
        private Object control;

        /**
         * Crea una nueva ventana FrmAsignarHabitacionManual.
         * Inicializa los componentes de la interfaz y carga los pisos disponibles.
         * 
         * @param control Controlador para la logica de asignacion
         */
        public FrmAsignarHabitacionManual(Object control) {
                this.control = control;
                initComponents();
                cargarPisos();
        }

        /**
         * Carga los pisos disponibles en el comboBox de seleccion de piso.
         * Deshabilita el comboBox de numeros de habitacion hasta que se seleccione un
         * piso.
         */
        private void cargarPisos() {
                if (control instanceof ControlAltaResidente) {
                        List<Integer> pisos = ((ControlAltaResidente) control).getPisosDisponibles();
                        for (Integer piso : pisos) {
                                comboBoxPiso.addItem(String.valueOf(piso));
                        }
                        comboBoxNumeros.setEnabled(false);
                } else if (control instanceof ControlActualizarResidente) {
                        List<Integer> pisos = ((ControlActualizarResidente) control).getPisosDisponibles();
                        for (Integer piso : pisos) {
                                comboBoxPiso.addItem(String.valueOf(piso));
                        }
                        ResidenteDTO residente = ((ControlActualizarResidente) control).getResidente();
                        if (residente.getIdHabitacion() != null) {
                                IAdministradorHabitaciones adminHabitaciones = new AdministradorHabitacionesFachada();
                                try {
                                        HabitacionDTO habitacion = adminHabitaciones.obtenerHabitacion(
                                                        new HabitacionDTO(residente.getIdHabitacion()));
                                        comboBoxPiso.setSelectedItem(String.valueOf(habitacion.getPiso()));
                                } catch (NegocioException e) {
                                        JOptionPane.showMessageDialog(this,
                                                        "Error al obtener la habitación del residente: "
                                                                        + e.getMessage(),
                                                        "Error", JOptionPane.ERROR_MESSAGE);
                                }
                        }
                        comboBoxNumeros.setEnabled(true);
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents

        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                comboBoxNumeros = new javax.swing.JComboBox<>();
                labelNumHabitacion1 = new javax.swing.JLabel();
                labelNumHabitacion3 = new javax.swing.JLabel();
                // :3

                labelNumHabitacion4 = new javax.swing.JLabel();
                labelHabitacionSeleccionada = new javax.swing.JLabel();
                comboBoxPiso = new javax.swing.JComboBox<>();
                btnAsignar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(228, 233, 236));

                jPanel3.setBackground(new java.awt.Color(255, 255, 255));

                jPanel4.setBackground(new java.awt.Color(27, 44, 87));

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 8, Short.MAX_VALUE));

                jPanel5.setBackground(new java.awt.Color(255, 255, 255));

                comboBoxNumeros.setForeground(new java.awt.Color(27, 44, 87));
                comboBoxNumeros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
                comboBoxNumeros.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                comboBoxNumerosItemStateChanged(evt);
                        }
                });

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(comboBoxNumeros,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                271,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(97, Short.MAX_VALUE)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(comboBoxNumeros,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(27, Short.MAX_VALUE)));

                labelNumHabitacion1.setBackground(new java.awt.Color(27, 44, 87));
                labelNumHabitacion1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
                labelNumHabitacion1.setForeground(new java.awt.Color(27, 44, 87));
                labelNumHabitacion1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                labelNumHabitacion1.setText("Habitaciones disponibles");
                labelNumHabitacion1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

                labelNumHabitacion3.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
                labelNumHabitacion3.setForeground(new java.awt.Color(102, 102, 102));
                labelNumHabitacion3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                labelNumHabitacion3.setText("Piso:");
                labelNumHabitacion3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

                labelNumHabitacion4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
                labelNumHabitacion4.setForeground(new java.awt.Color(102, 102, 102));
                labelNumHabitacion4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                labelNumHabitacion4.setText("Habitación seleccionada:");
                labelNumHabitacion4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

                labelHabitacionSeleccionada.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 14)); // NOI18N
                labelHabitacionSeleccionada.setForeground(new java.awt.Color(27, 44, 87));
                labelHabitacionSeleccionada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                labelHabitacionSeleccionada.setText("0000");
                labelHabitacionSeleccionada.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

                comboBoxPiso.setForeground(new java.awt.Color(27, 44, 87));
                comboBoxPiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
                comboBoxPiso.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                comboBoxPisoItemStateChanged(evt);
                        }
                });

                btnAsignar.setBackground(new java.awt.Color(107, 225, 251));
                btnAsignar.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 13)); // NOI18N
                btnAsignar.setForeground(new java.awt.Color(27, 44, 87));
                btnAsignar.setText("Asignar Habitación");
                btnAsignar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 225, 251), 1, true));
                btnAsignar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAsignarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(22, 22, 22)
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jPanel5,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                jPanel3Layout.createSequentialGroup()
                                                                                                                                                .addComponent(labelNumHabitacion1)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(labelNumHabitacion3))
                                                                                                                .addComponent(jPanel4,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(comboBoxPiso,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(16, 16, 16)
                                                                                                .addComponent(labelNumHabitacion4)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(labelHabitacionSeleccionada,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                66,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btnAsignar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                250,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(40, Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                                .createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(12, 12, 12)
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(labelNumHabitacion3)
                                                                                                                .addComponent(comboBoxPiso,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                40,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel3Layout.createSequentialGroup()
                                                                                                                .addContainerGap()
                                                                                                                .addComponent(labelNumHabitacion1)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(52, 52, 52)
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(labelNumHabitacion4)
                                                                                                                .addComponent(labelHabitacionSeleccionada)))
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(38, 38, 38)
                                                                                                .addComponent(btnAsignar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                40,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(17, 17, 17)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * Maneja el evento de cambio en el comboBox de numeros de habitacion.
         * Actualiza la etiqueta de habitacion seleccionada con el piso y numero
         * elegidos.
         * 
         * @param evt Evento de cambio de estado del comboBox
         */
        private void comboBoxNumerosItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboBoxNumerosItemStateChanged
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                        if (!comboBoxNumeros.getSelectedItem().toString().equals("Seleccionar")) {
                                labelHabitacionSeleccionada.setText(comboBoxPiso.getSelectedItem().toString() + " - "
                                                + comboBoxNumeros.getSelectedItem().toString());
                        } else {
                                labelHabitacionSeleccionada.setText("0000");
                        }
                }
        }// GEN-LAST:event_comboBoxNumerosItemStateChanged

        /**
         * Maneja el evento de cambio en el comboBox de pisos.
         * Habilita y carga los numeros de habitaciones disponibles para el piso
         * seleccionado,
         * o deshabilita el comboBox si no se selecciona un piso valido.
         * 
         * @param evt Evento de cambio de estado del comboBox
         */
        private void comboBoxPisoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboBoxPisoItemStateChanged
                if (comboBoxPiso.getSelectedItem().toString().equals("Seleccionar")) {
                        comboBoxNumeros.removeAllItems();
                        comboBoxNumeros.addItem("Seleccionar");
                        comboBoxNumeros.setEnabled(false);
                } else {
                        comboBoxNumeros.setEnabled(true);
                        cargarNumeros(Integer.parseInt(comboBoxPiso.getSelectedItem().toString()));
                }

        }// GEN-LAST:event_comboBoxPisoItemStateChanged

        /**
         * Carga los numeros de habitaciones disponibles para un piso especifico.
         * Actualiza el comboBox de numeros de habitacion con las opciones disponibles.
         * 
         * @param piso Piso seleccionado para cargar las habitaciones
         */
        private void cargarNumeros(int piso) {
                if (control instanceof ControlAltaResidente) {
                        try {
                                List<HabitacionDTO> habitaciones = ((ControlAltaResidente) control)
                                                .obtenerHabitacionesDisponiblesParaResidente(((ControlAltaResidente) control).getResidente(), piso);
                                comboBoxNumeros.removeAllItems();
                                comboBoxNumeros.addItem("Seleccionar");
                                for (HabitacionDTO habitacion : habitaciones) {
                                        comboBoxNumeros.addItem(String.valueOf(habitacion.getNumero()));
                                }
                        } catch (NegocioException ex) {
                                JOptionPane.showMessageDialog(null, "Error al cargar habitaciones: " + ex.getMessage(), "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                } else if (control instanceof ControlActualizarResidente) {
                        try {
                                List<HabitacionDTO> habitaciones = ((ControlActualizarResidente) control)
                                                .obtenerHabitacionesDisponiblesParaResidente(((ControlActualizarResidente) control).getResidente(), piso);
                                comboBoxNumeros.removeAllItems();
                                comboBoxNumeros.addItem("Seleccionar");
                                for (HabitacionDTO habitacion : habitaciones) {
                                        comboBoxNumeros.addItem(String.valueOf(habitacion.getNumero()));
                                }
                                ResidenteDTO residente = ((ControlActualizarResidente) control).getResidente();
                                if(residente.getIdHabitacion() != null) {
                                        IAdministradorHabitaciones adminHabitaciones = new AdministradorHabitacionesFachada();
                                        HabitacionDTO habitacion = adminHabitaciones.obtenerHabitacion(
                                                        new HabitacionDTO(residente.getIdHabitacion()));
                                        comboBoxNumeros.setSelectedItem(String.valueOf(habitacion.getNumero()));
                                }

                        } catch (NegocioException ex) {
                                JOptionPane.showMessageDialog(null, "Error al cargar habitaciones: " + ex.getMessage(), "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                }
        }

        /**
         * Maneja el evento del boton Asignar habitacion.
         * Valida la seleccion de piso y numero, solicita confirmacion y asigna la
         * habitacion al residente.
         * Muestra mensajes de exito o error segun el resultado y cierra la ventana si
         * la asignacion es exitosa.
         * 
         * @param evt Evento de accion del boton
         */
        private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAsignarActionPerformed
                try {
                        String piso = comboBoxPiso.getSelectedItem().toString();
                        String numero = comboBoxNumeros.getSelectedItem().toString();
                        if (piso.equals("Seleccionar") || numero.equals("Seleccionar")) {
                                throw new Exception("Debe de seleccionar un piso y un numero de habitación");
                        }
                        int confirmacion = JOptionPane.showConfirmDialog(
                                        this,
                                        "Seguro que desea asignar la habitación?",
                                        "Confirmar",
                                        JOptionPane.YES_NO_OPTION);
                        if (confirmacion == JOptionPane.YES_OPTION) {
                                if(control instanceof ControlAltaResidente) {
                                        ((ControlAltaResidente) control).asignarHabitacion(((ControlAltaResidente) control).getResidente(),
                                                        new HabitacionDTO(Integer.parseInt(piso), Integer.parseInt(numero)));
                                        JOptionPane.showMessageDialog(this, "Habitación asignada con exito", "Informacion",
                                                        JOptionPane.INFORMATION_MESSAGE);
                                        ((ControlAltaResidente) control).mostrarAltaExitosa();
                                        this.dispose();
                                } else if (control instanceof ControlActualizarResidente) {
                                        ((ControlActualizarResidente) control).actualizarHabitacion(((ControlActualizarResidente) control).getResidente(),
                                                        new HabitacionDTO(Integer.parseInt(piso), Integer.parseInt(numero)));
                                        JOptionPane.showMessageDialog(this, "Habitación asignada con exito", "Informacion",
                                                        JOptionPane.INFORMATION_MESSAGE);
                                        ((ControlActualizarResidente) control).acabarCaso();
                                        this.dispose();
                                }
                        }
                } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }// GEN-LAST:event_btnAsignarActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAsignar;
        private javax.swing.JComboBox<String> comboBoxNumeros;
        private javax.swing.JComboBox<String> comboBoxPiso;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JLabel labelHabitacionSeleccionada;
        private javax.swing.JLabel labelNumHabitacion1;
        private javax.swing.JLabel labelNumHabitacion3;
        private javax.swing.JLabel labelNumHabitacion4;
        // End of variables declaration//GEN-END:variables
}
