/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author rauln
 */
public class FrmReporteMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form FrmReporteMantenimiento
     */
    public FrmReporteMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        labelTextTitulo = new javax.swing.JLabel();
        labelTextInformacion = new javax.swing.JLabel();
        labelTextHabitaciones = new javax.swing.JLabel();
        comboBoxResidentes = new javax.swing.JComboBox<>();
        labelTextResidentes = new javax.swing.JLabel();
        comboBoxHabitaciones = new javax.swing.JComboBox<>();
        labelTextInformacion1 = new javax.swing.JLabel();
        labelTextHorario1 = new javax.swing.JLabel();
        comboBoxSegundaHoraRango = new javax.swing.JComboBox<>();
        labelTextHorario2 = new javax.swing.JLabel();
        comboBoxPrimerHoraRango = new javax.swing.JComboBox<>();
        panelCajaTexto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaTextoProblema = new javax.swing.JTextArea();
        labelTextInformacion2 = new javax.swing.JLabel();
        botonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTextTitulo.setFont(new java.awt.Font("Montserrat Medium", 1, 24)); // NOI18N
        labelTextTitulo.setText(" GENERAR REPORTE DE MANTENIMIENTO ");
        fondo.add(labelTextTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 18, -1, -1));

        labelTextInformacion.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        labelTextInformacion.setForeground(new java.awt.Color(204, 204, 204));
        labelTextInformacion.setText("INFORMACIÓN");
        fondo.add(labelTextInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        labelTextHabitaciones.setFont(new java.awt.Font("Montserrat Medium", 1, 18)); // NOI18N
        labelTextHabitaciones.setText("HABITACIÓN");
        fondo.add(labelTextHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 30));

        comboBoxResidentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(comboBoxResidentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 110, 30));

        labelTextResidentes.setFont(new java.awt.Font("Montserrat Medium", 1, 18)); // NOI18N
        labelTextResidentes.setText("RESIDENTE");
        fondo.add(labelTextResidentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, 30));

        comboBoxHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(comboBoxHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 110, 30));

        labelTextInformacion1.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        labelTextInformacion1.setForeground(new java.awt.Color(204, 204, 204));
        labelTextInformacion1.setText("HORARIO PREFERENTE DE VISITA");
        fondo.add(labelTextInformacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        labelTextHorario1.setFont(new java.awt.Font("Montserrat Medium", 1, 18)); // NOI18N
        labelTextHorario1.setText("ENTRE");
        fondo.add(labelTextHorario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 30));

        comboBoxSegundaHoraRango.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(comboBoxSegundaHoraRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 110, 30));

        labelTextHorario2.setFont(new java.awt.Font("Montserrat Medium", 1, 18)); // NOI18N
        labelTextHorario2.setText("Y");
        fondo.add(labelTextHorario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, 30));

        comboBoxPrimerHoraRango.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(comboBoxPrimerHoraRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 110, 30));

        panelCajaTexto.setBackground(new java.awt.Color(255, 255, 255));

        textAreaTextoProblema.setColumns(20);
        textAreaTextoProblema.setRows(5);
        jScrollPane1.setViewportView(textAreaTextoProblema);

        javax.swing.GroupLayout panelCajaTextoLayout = new javax.swing.GroupLayout(panelCajaTexto);
        panelCajaTexto.setLayout(panelCajaTextoLayout);
        panelCajaTextoLayout.setHorizontalGroup(
            panelCajaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );
        panelCajaTextoLayout.setVerticalGroup(
            panelCajaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );

        fondo.add(panelCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 548, 175));

        labelTextInformacion2.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        labelTextInformacion2.setForeground(new java.awt.Color(204, 204, 204));
        labelTextInformacion2.setText("DESCRIPCIÓN DEL PROBLEMA");
        fondo.add(labelTextInformacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        botonEnviar.setBackground(new java.awt.Color(113, 209, 153));
        botonEnviar.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        botonEnviar.setText("ENVIAR");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });
        fondo.add(botonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 100, 30));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviar;
    private javax.swing.JComboBox<String> comboBoxHabitaciones;
    private javax.swing.JComboBox<String> comboBoxPrimerHoraRango;
    private javax.swing.JComboBox<String> comboBoxResidentes;
    private javax.swing.JComboBox<String> comboBoxSegundaHoraRango;
    private javax.swing.JPanel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTextHabitaciones;
    private javax.swing.JLabel labelTextHorario1;
    private javax.swing.JLabel labelTextHorario2;
    private javax.swing.JLabel labelTextInformacion;
    private javax.swing.JLabel labelTextInformacion1;
    private javax.swing.JLabel labelTextInformacion2;
    private javax.swing.JLabel labelTextResidentes;
    private javax.swing.JLabel labelTextTitulo;
    private javax.swing.JPanel panelCajaTexto;
    private javax.swing.JTextArea textAreaTextoProblema;
    // End of variables declaration//GEN-END:variables
}
