package presentacion;

import control.ControlGenerarReferenciaPago;
import dto.ReferenciaPagoDTO;
import dto.ResidenteDTO;
import excepciones.NegocioException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FrmRefPago extends JFrameBase {

    ControlGenerarReferenciaPago control;

    /**
     * Creates new form FrmRefPago
     */
    public FrmRefPago(ControlGenerarReferenciaPago control) {
        super();
        this.control = control;
        initComponents();
    }

    public void cargarReferenciaPago(ReferenciaPagoDTO referencia){
        //extraer datos de referencia
        String matricula = referencia.getMatriculaResidente();
        String nombreCompleto = referencia.getNombreResidente();
        String carrera = referencia.getCarreraResidente();
        String tipo = referencia.getTipoResidente();
        String correo = referencia.getCorreoResidente();
        String numReferencia = referencia.getReferencia();
        String folio = referencia.getFolio();
        String concepto = referencia.getConcepto();
        BigDecimal importe = referencia.getImporte();
        Date fechaGeneracion = referencia.getFechaGeneracion();
        Date fechaVencimiento = referencia.getFechaVencimiento();
        
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        this.txtFechaGen.setText(formatoFecha.format(fechaGeneracion));

        //llenado de campos
        this.txtNombreResidente.setText(nombreCompleto);
        this.txtTipoResidente.setText("Tipo de residente: " + tipo);
        this.txtCarrera.setText("Programa educativo: " + carrera);
        this.txtMatricula.setText("ID: " + matricula);
        this.txtCorreo.setText("Correo: " + correo);
        this.txtReferencia.setText(numReferencia);
        this.txtFolio.setText(folio);
        this.txtConcepto.setText(concepto);
        this.txtImporte.setText("$"+String.valueOf(importe));
        this.txtFechaGen.setText(formatoFecha.format(fechaGeneracion));
        this.txtFechaVen.setText(formatoFecha.format(fechaVencimiento));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblReferenciaPago = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        lblLogoResi = new javax.swing.JLabel();
        pnlLinea = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        txtNombreResidente = new javax.swing.JLabel();
        txtTipoResidente = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblReferencia = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JLabel();
        lblFolio = new javax.swing.JLabel();
        txtFolio = new javax.swing.JLabel();
        lblConcepto = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JLabel();
        lblFechaGen = new javax.swing.JLabel();
        lblFechaVen = new javax.swing.JLabel();
        lblClabe = new javax.swing.JLabel();
        txtClabe = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();
        txtImporte = new javax.swing.JLabel();
        txtFechaGen = new javax.swing.JLabel();
        txtFechaVen = new javax.swing.JLabel();
        logoBBVA = new javax.swing.JLabel();
        pnlLinea1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 44, 87));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(27, 44, 87));

        lblReferenciaPago.setFont(new java.awt.Font("Apple LiGothic", 0, 46)); // NOI18N
        lblReferenciaPago.setForeground(new java.awt.Color(245, 253, 255));
        lblReferenciaPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReferenciaPago.setText("Referencia de Pago");
        lblReferenciaPago.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnEnviar.setBackground(new java.awt.Color(107, 225, 251));
        btnEnviar.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(27, 44, 87));
        btnEnviar.setText("Enviar por correo");
        btnEnviar.setBorderPainted(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblLogoResi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoResi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logotipo Residencias Estudiantiles Horizontal.png"))); // NOI18N

        pnlLinea.setBackground(new java.awt.Color(107, 225, 251));

        javax.swing.GroupLayout pnlLineaLayout = new javax.swing.GroupLayout(pnlLinea);
        pnlLinea.setLayout(pnlLineaLayout);
        pnlLineaLayout.setHorizontalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        pnlLineaLayout.setVerticalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        btnRegresar.setBackground(new java.awt.Color(37, 55, 95));
        btnRegresar.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(107, 225, 251));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 225, 251), 1, true));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        txtNombreResidente.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreResidente.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 24)); // NOI18N
        txtNombreResidente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreResidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombreResidente.setText("Nombre del Residente");

        txtTipoResidente.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 11)); // NOI18N
        txtTipoResidente.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoResidente.setText("Tipo de residente placholder");

        txtCarrera.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 11)); // NOI18N
        txtCarrera.setForeground(new java.awt.Color(255, 255, 255));
        txtCarrera.setText("Programa educativo: Placeholder");

        txtMatricula.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 11)); // NOI18N
        txtMatricula.setForeground(new java.awt.Color(255, 255, 255));
        txtMatricula.setText("ID: 0000000000");

        txtCorreo.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 11)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setText("Correo: Placeholder");

        jPanel2.setBackground(new java.awt.Color(45, 64, 114));

        lblReferencia.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lblReferencia.setForeground(new java.awt.Color(255, 255, 255));
        lblReferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReferencia.setText("Referencia:");

        txtReferencia.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        txtReferencia.setForeground(new java.awt.Color(255, 255, 255));
        txtReferencia.setText("ABC000HAB01-REF000");

        lblFolio.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lblFolio.setForeground(new java.awt.Color(255, 255, 255));
        lblFolio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFolio.setText("Folio:");

        txtFolio.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        txtFolio.setForeground(new java.awt.Color(255, 255, 255));
        txtFolio.setText("REF00");

        lblConcepto.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lblConcepto.setForeground(new java.awt.Color(255, 255, 255));
        lblConcepto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConcepto.setText("Concepto:");

        txtConcepto.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        txtConcepto.setForeground(new java.awt.Color(255, 255, 255));
        txtConcepto.setText("Residencias ITSON - Habitacion 1");

        lblFechaGen.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lblFechaGen.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaGen.setText("Fecha de generacion:");

        lblFechaVen.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lblFechaVen.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaVen.setText("Fecha de vencimiento:");

        lblClabe.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lblClabe.setForeground(new java.awt.Color(255, 255, 255));
        lblClabe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClabe.setText("CLABE:");

        txtClabe.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        txtClabe.setForeground(new java.awt.Color(255, 255, 255));
        txtClabe.setText("123456789123456789");

        lblImporte.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lblImporte.setForeground(new java.awt.Color(255, 255, 255));
        lblImporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImporte.setText("Importe:");

        txtImporte.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        txtImporte.setForeground(new java.awt.Color(255, 255, 255));
        txtImporte.setText("$2000.00");

        txtFechaGen.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        txtFechaGen.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaGen.setText("01/01/2025");

        txtFechaVen.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        txtFechaVen.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaVen.setText("01/01/2025");

        logoBBVA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoBBVA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BBVA_footer.png"))); // NOI18N

        pnlLinea1.setBackground(new java.awt.Color(107, 225, 251));

        javax.swing.GroupLayout pnlLinea1Layout = new javax.swing.GroupLayout(pnlLinea1);
        pnlLinea1.setLayout(pnlLinea1Layout);
        pnlLinea1Layout.setHorizontalGroup(
            pnlLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlLinea1Layout.setVerticalGroup(
            pnlLinea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblClabe, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClabe, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFechaGen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaVen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaGen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaVen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoBBVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlLinea1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReferencia)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFolio)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcepto)
                    .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClabe)
                    .addComponent(txtClabe, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImporte)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaGen, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaGen))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaVen, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaVen))
                .addGap(28, 28, 28)
                .addComponent(logoBBVA, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlLinea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(72, 72, 72)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCarrera)
                                                .addComponent(txtTipoResidente)
                                                .addComponent(txtMatricula)
                                                .addComponent(txtCorreo)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(113, 113, 113)
                                            .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE))
                            .addComponent(txtNombreResidente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReferenciaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReferenciaPago)
                    .addComponent(lblLogoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(txtNombreResidente)
                        .addGap(28, 28, 28)
                        .addComponent(txtTipoResidente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCarrera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCorreo)
                        .addGap(44, 44, 44)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        try {
            control.enviarReferencia();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(
                        this,
                        "Error: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        control.volverIngresarIDEstudiante();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClabe;
    private javax.swing.JLabel lblConcepto;
    private javax.swing.JLabel lblFechaGen;
    private javax.swing.JLabel lblFechaVen;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblLogoResi;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JLabel lblReferenciaPago;
    private javax.swing.JLabel logoBBVA;
    private javax.swing.JPanel pnlLinea;
    private javax.swing.JPanel pnlLinea1;
    private javax.swing.JLabel txtCarrera;
    private javax.swing.JLabel txtClabe;
    private javax.swing.JLabel txtConcepto;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtFechaGen;
    private javax.swing.JLabel txtFechaVen;
    private javax.swing.JLabel txtFolio;
    private javax.swing.JLabel txtImporte;
    private javax.swing.JLabel txtMatricula;
    private javax.swing.JLabel txtNombreResidente;
    private javax.swing.JLabel txtReferencia;
    private javax.swing.JLabel txtTipoResidente;
    // End of variables declaration//GEN-END:variables
}
