package presentacion;

import control.ControlGenerarReferenciaPago;


public class FrmRefPagoEnviada extends JFrameBase {

    private ControlGenerarReferenciaPago control;

    /**
     * Creates new form FrmAsignarHabitacion
     */
    public FrmRefPagoEnviada(ControlGenerarReferenciaPago control) {
        super();
        this.control = control;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnGenerarOtraReferencia = new javax.swing.JButton();
        btnRegresarInicio = new javax.swing.JButton();
        lblNombreResidente = new javax.swing.JLabel();
        lblLogoResi = new javax.swing.JLabel();
        lblPreview = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 44, 87));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        lblTitulo.setFont(new java.awt.Font("Kohinoor Gujarati", 1, 260)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(107, 225, 251));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("✔");

        btnGenerarOtraReferencia.setBackground(new java.awt.Color(107, 225, 251));
        btnGenerarOtraReferencia.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        btnGenerarOtraReferencia.setForeground(new java.awt.Color(27, 44, 87));
        btnGenerarOtraReferencia.setText("Generar otra referencia");
        btnGenerarOtraReferencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnGenerarOtraReferencia.setBorderPainted(false);
        btnGenerarOtraReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarOtraReferenciaActionPerformed(evt);
            }
        });

        btnRegresarInicio.setBackground(new java.awt.Color(27, 44, 87));
        btnRegresarInicio.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        btnRegresarInicio.setForeground(new java.awt.Color(107, 225, 251));
        btnRegresarInicio.setText("Regresar a inicio");
        btnRegresarInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 225, 251), 2, true));
        btnRegresarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarInicioActionPerformed(evt);
            }
        });

        lblNombreResidente.setFont(new java.awt.Font("Apple LiGothic", 0, 100)); // NOI18N
        lblNombreResidente.setForeground(new java.awt.Color(107, 225, 251));
        lblNombreResidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreResidente.setText("¡Referencia Enviada!");
        lblNombreResidente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblLogoResi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logotipo Residencias Estudiantiles Horizontal.png"))); // NOI18N

        lblPreview.setFont(new java.awt.Font("Apple LiGothic", 0, 24)); // NOI18N
        lblPreview.setForeground(new java.awt.Color(245, 253, 255));
        lblPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreview.setText("Referencia de pago enviada al correo institucional del alumno!");
        lblPreview.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btnRegresarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(btnGenerarOtraReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 210, Short.MAX_VALUE))
            .addComponent(lblPreview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreResidente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogoResi)
                .addGap(402, 402, 402))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblLogoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreResidente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarOtraReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarInicioActionPerformed
       control.acabarCaso();
    }//GEN-LAST:event_btnRegresarInicioActionPerformed

    private void btnGenerarOtraReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarOtraReferenciaActionPerformed
        
    }//GEN-LAST:event_btnGenerarOtraReferenciaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarOtraReferencia;
    private javax.swing.JButton btnRegresarInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogoResi;
    private javax.swing.JLabel lblNombreResidente;
    private javax.swing.JLabel lblPreview;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
